# This workflow will run tests using node and then publish to vercel when a release is created
name: Publish to Vercel

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx turbo run lint
      - run: npx turbo run build:app

      - name: Sav app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: dist/app

  publish:

    needs: build

    runs-on: ubuntu-latest

    environment: Production

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download previously built app artifacts
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Pull Vercel Environment Information
        run: npx vercel@latest pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: npx vercel@latest build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel@latest deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
